
POST http://127.0.0.1:5000/auth/
Content-Type: application/json

{
  "username": "JAlex",
  "password": "dwf"
}

###

POST http://127.0.0.1:5000/auth/
Content-Type: application/json

{
  "username": "Alina",
  "password": "qwertY"
}

####

POST http://localhost:5000/auth/
Content-Type: application/json

{
  "username": "Admin",
  "password": "test"
}
###
PUT http://localhost:5000/auth/
Content-Type: application/json

{
  "refresh_token": "JWT_REFRESH_TOKEN"
}